### ISSUE TITLE
[Question] Why KSP?

### ISSUE THREAD

**Issue by esafirm** [meganz/mobile-analytics#1]
Hi team, thanks for making this code public, there are a lot of things that can be learned from it.

It's fascinating that in this project we are using KSP to generate the event object that will be used in Android and iOS.
Typically, in this case, the object got generated from a different source for example a proto or a JSON file.

But, I keep wondering if KSP is the best solution for this, for example couple of drawbacks:

1. Unnecessary code created and distributed, in this case, the annotated interfaces
2. ID is not visible until you compile the code or check into the generated JSON file that can be missed to be committed
3. Validation of duplicated ID needs to be created in another process (outside KSP), in this case, the linter

I think, using a data file like JSON, proto, or even YAML as a source of truth, assisted with kotlinpoet (since we still want to use KMP) can be more efficient because we can tackle the above 3 issues.

**Comment by DoMegaNZ** [comment]
KSP was a tool with which we were already familiar, and as we had already created an initial implementation in our Android app, it was a logical next step in our attempt to make the functionality available cross platform.

Also, our priorities were to make adding new events bot really simple for devs to do, but still limiting them from adding events in ways that violate our guidelines.

But there will always be better ways of doing things, and we usually find most of them in hindsight. The question then simply becomes an equation of whether it is worth the effort to change something that already works but has some minor issues, vs putting our effort into other areas that are more pressing or important.
